### ISSUE TITLE
[bug] 无法监听应用程序数据，在 数据集合-监听-筛选要监听的程序-提示暂无数据

### ISSUE THREAD

**Issue by weiqi57** [shion-app/shion#12]
### Describe the bug

下载后打开无法在监听程序页面显示程序，刷新和重新启动均无效。
查看帮助->开发者工具->控制台中有报错，不确定是否有关。
Failed to load resource: the server responded with a status of 400 (Bad Request)
program not found
...

### Version

v0.11.0

### Steps to reproduce

在其他平台上，按作者建议下载[watcher项目中](https://github.com/shion-app/watcher/blob/main/powershell/get-program.ps1)
的脚本get-program.ps1在我本地电脑运行后报错如下：
所在位置 D:\Downloads\get-program.ps1:52 字符: 1
+ }
+ ~
表达式或语句中包含意外的标记“}”。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
    
 经测试需要删除
 if (-not $processPath) {
        Continue
    }
 函数前后的中文注释后可以编译，但无输出
 
 删除全部的中文注释后，可以正常输出。

    
 

### Additional information

 
 powershell版本：5.1.22621.2506
 系统：win11 23H2 22631.3593
 
![image](https://github.com/shion-app/shion/assets/68769177/e4f0d4c7-3658-493c-9c6e-a0d2fbd33e8a)

![image](https://github.com/shion-app/shion/assets/68769177/1afe97cb-418b-4130-ac83-b658828b5dfc)

**Comment by hanaTsuk1** [comment]
已修复，暂时以删除注释处理

相关情况：[Powershell编码原因导致部分代码不执行](https://blog.csdn.net/zhouzme/article/details/118635153)

**Comment by weiqi57** [comment]
我试了下11.2版本还是不行，不知道是不是我环境的问题，下面是开发者工具中的报错信息和之前一样。
![image](https://github.com/shion-app/shion/assets/68769177/5c4ab52e-bef8-4de6-81c9-3bd7e2ffaa3a)

**Comment by hanaTsuk1** [comment]
一个猜测  虽然你有powershell  但环境变量里已经被删除了  导致无法调用

[试下这个](https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr#answer-65871920)

**Comment by weiqi57** [comment]
解决了，确实是环境变量的问题，感谢作者指导 :)
