### ISSUE TITLE
[bug] 运行软件的卸载程序把我电脑内的所有adobe软件也全都一起删除了，数据都没了

### ISSUE THREAD

**Issue by Long-louis** [shion-app/shion#13]
### Describe the bug

 运行软件的卸载程序把我电脑内的所有adobe软件也全都一起删除了，数据都没了。运行之后我一看写在界面的显示把我adobe的ps和pr，lightroom全都删的一干二净这个时候已经抢救不了了，只剩下一点残留的pr文件，太坑人了
![image](https://github.com/shion-app/shion/assets/41790869/3260cd89-fcdb-412f-9aa4-bc22ccafde66)

### Version

v0.8

**Comment by hanaTsuk1** [comment]
你在安装的时候没有给shion创建一个单独的文件夹 而是使用的路径"D:\Program_Files\Adobe"是吗？
如果是的话 卸载软件会删除安装路径下的全部文件是正常情况

如果对此存在质疑可以重新尝试一次进行验证，卸载程序是由[tauri](https://tauri.app/zh-cn/)提供支持，是经过使用验证了的
对于你受到的损失表示非常遗憾

**Comment by hanaTsuk1** [comment]
tauri已对此情况进行改进，我将在新版本跟进
https://github.com/tauri-apps/tauri/issues/9475
