### ISSUE TITLE
[bug] 筛选要监听的程序显示暂无数据

### ISSUE THREAD

**Issue by decajoin** [shion-app/shion#14]
### Describe the bug

在使用监听功能时，进入到筛选监听的程序界面显示暂无数据
![image](https://github.com/shion-app/shion/assets/134501931/f5d2be3e-3338-40de-afcc-87550a67fd0a)
在关闭的issue中，看见了类似的问题但是原谅我没有看懂，希望作者能够提供一点帮助，感谢！

系统信息：
版本	Windows 11 家庭中文版
版本	23H2

### Version

v0.11.2

**Comment by hanaTsuk1** [comment]
1. 点击左下角开始菜单，输出cmd，回车运行，在弹出来的窗口输入"powershell"
2. 如果有报错，则是环境变量的问题，把`C:\WINDOWS\System32\WindowsPowerShell\v1.0\`或者`%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`添加到**path**里

[如何添加环境变量](https://zhuanlan.zhihu.com/p/646247339)
