### ISSUE TITLE
[bug] 监听程序添加不了

### ISSUE THREAD

**Issue by xutengyang** [shion-app/shion#18]
### Describe the bug

识别不到监听程序，添加时显示暂无数据
![image](https://github.com/shion-app/shion/assets/74175801/2a8dfea8-7f2c-459e-b364-9a800d95aca4)

### Version

v0.11.2

**Comment by hanaTsuk1** [comment]
看一下这个https://github.com/shion-app/shion/issues/14，是不是一个问题
