### ISSUE TITLE
[bug] 导入浏览器历史记录提示导入出错

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#19]
### Describe the bug

![image](https://github.com/shion-app/shion/assets/53282874/2f222565-f66a-4a90-a201-22183926dd99)

### Version

v0.11.3

### Steps to reproduce

1、点击左上角视图
2、菜单点击“浏览器历史记录”
3、最后点击导入数据和确认

**Comment by q943613777** [comment]
电脑上都安装有安装 Chrome、Edge、Firefox浏览器

**Comment by hanaTsuk1** [comment]
看一下这个 https://github.com/shion-app/shion/discussions/16 ，是不是一个问题

**Comment by q943613777** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by q943613777** [comment]
> 看一下这个 #16 ，是不是一个问题看一下这个 #16 ，是不是一个问题 看一下这个 #16 ，是不是一个问题

按照帖子的方法弄好了，感谢🙏

**Comment by aijgag** [comment]
> 看一下这个 #16 ，是不是一个问题

你好，我也遇到了相同的问题，但上面的解决措施对我没用（我只使用edge和chrome），这是我这里的报错，感谢帮助
![image](https://github.com/shion-app/shion/assets/126999802/a47efe2e-f749-49d4-ac4d-2c45c1b30663)

**Comment by hanaTsuk1** [comment]
@aijgag 
chrome路径是`AppData/Local/Google/Chrome/User Data/*/History`
edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History`
*一般是Default，下面有个History的文件
这个urls的表存着历史记录，你做过什么操作吗

**Comment by aijgag** [comment]
> @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗

感谢你的帮助。我在删除chrome中的一个0kb的History文件后解决了这个问题

**Comment by hanaTsuk1** [comment]
> > @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗
> 
> 感谢你的帮助。我在删除chrome中的一个0kb的History文件后解决了这个问题

为什么会这样，是在default下面吗？chrome是只安装没有使用吗？还是多用户的原因？

**Comment by q943613777** [comment]
第一次安装使用就出现这个问题，暂时还不知道做了啥操作

**Comment by aijgag** [comment]
> > > @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗
> > 
> > 
> > 感谢你的帮助。我在删除chrome中的一个0kb的History文件后解决了这个问题
> 
> 为什么会这样，是在default下面吗？chrome是只安装没有使用吗？还是多用户的原因？

我清理的是`AppData/Local/Google/Chrome/User Data/Default/History`文件
可能是chrome使用频率比较少，历史记录在前几天手动清理过，我从未对chrome进行过操作
我仅在电脑上使用chrome浏览器
刚刚我在chrome留下历史记录后发现已删的History文件并未重新生成，但在shion对chrome的监控里却同步了我刚刚在chrome的历史记录；但同样的，我在edge浏览器留下新的历史记录后，其目录下‘AppData/Local/Microsoft/Edge/User Data/Default/History’文件是会实时更新的，我也不明白是哪里有问题

**Comment by hanaTsuk1** [comment]
> > > > @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗
> > > 
> > > 
> > > 感谢你的帮助。我在删除chrome中的一个0kb的History文件后解决了这个问题
> > 
> > 
> > 为什么会这样，是在default下面吗？chrome是只安装没有使用吗？还是多用户的原因？
> 
> 我清理的是`AppData/Local/Google/Chrome/User Data/Default/History`文件 可能是chrome使用频率比较少，历史记录在前几天手动清理过，我从未对chrome进行过操作 我仅在电脑上使用chrome浏览器 刚刚我在chrome留下历史记录后发现已删的History文件并未重新生成，但在shion对chrome的监控里却同步了我刚刚在chrome的历史记录；但同样的，我在edge浏览器留下新的历史记录后，其目录下‘AppData/Local/Microsoft/Edge/User Data/Default/History’文件是会实时更新的，我也不明白是哪里有问题

shion会扫描多个路径，*是通配符
那就说明你现在用的不是default下的，chrome右上角点头像可以新增用户，可以在`User Data`下按修改时间排序，看最新更新，就能找到当前使用的用户目录

**Comment by happytbs** [comment]
> @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗

在User Data里面找不到Default怎么办

**Comment by aijgag** [comment]
> > @aijgag chrome路径是`AppData/Local/Google/Chrome/User Data/*/History` edge路径是`AppData/Local/Microsoft/Edge/User Data/*/History` *一般是Default，下面有个History的文件 这个urls的表存着历史记录，你做过什么操作吗
> 
> 在User Data里面找不到Default怎么办

这个数据保存在C:\Users\用户名\AppData\Local\Microsoft\Edge\User Data里面的文件夹里，具体需要看你使用的配置文件是哪个。默认是会保存在Default文件夹里，但是如果你是添加过其他的配置文件，还需要查看Profile #文件夹。
其中#是数字
