### ISSUE TITLE
[bug] 同时打开两个浏览器，貌似会丢失掉一些记录

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#22]
### Describe the bug

![image](https://github.com/shion-app/shion/assets/53282874/5bdb119a-9443-436d-841e-304ceeb20a89)

附上了一份日志文件

### Version

v0.11.4

### Steps to reproduce

1、打开Firefox并浏览网页
2、打开edge并浏览网页
3、查看时间线

### Additional information

[shion.log](https://github.com/user-attachments/files/15515122/shion.log)

**Comment by hanaTsuk1** [comment]
一旦刷新时间线数据，就会去拉浏览器数据，但此时本地数据库不一定更新了
一旦拉取完，就会有个时间标记，在这个时间之前的数据都不会再次拉取，也不会去比较是否更新

![chrome_yHCKj57pul](https://github.com/shion-app/shion/assets/101488209/63bde6d0-cd4c-4b6b-9066-b4b5ae49de79)

**Comment by q943613777** [comment]
> 一旦刷新时间线数据，就会去拉浏览器数据，但此时本地数据库不一定更新了 一旦拉取完，就会有个时间标记，在这个时间之前的数据都不会再次拉取，也不会去比较是否更新
> 
> ![chrome_yHCKj57pul](https://private-user-images.githubusercontent.com/101488209/335765287-63bde6d0-cd4c-4b6b-9066-b4b5ae49de79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTM5NTQsIm5iZiI6MTcxNzIxMzY1NCwicGF0aCI6Ii8xMDE0ODgyMDkvMzM1NzY1Mjg3LTYzYmRlNmQwLWNkNGMtNGI2Yi05MDY2LWI0YjVhZTQ5ZGU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQwMzQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjllOTllMzlmMzc0NTJlYzhiY2Q0ZDdiYTNiMzRkZGVlNjlmMDA5NTUwYzc1OTI0OTNhMWQyZDA3NTBkY2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vGqAwO2Zdb6-tJxuDH7Ds1oli-UOz1lAW8kU9WiquaQ)

好的，谢谢
