### ISSUE TITLE
[bug] 偶尔会出现刷新的时候会一直卡住，刷新不出新的时间线

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#23]
### Describe the bug

![1717170373372_d](https://github.com/shion-app/shion/assets/53282874/fd64d966-bf68-47d5-bbe5-fb7c5b30383f)

### Version

v0.11.4

### Steps to reproduce

1、打开时间线
2、点击右下角刷新按钮

### Additional information

[shion.log](https://github.com/user-attachments/files/15515946/shion.log)

**Comment by hanaTsuk1** [comment]
1. 这个情况出现了几次
2. 出现这个问题之后，有切换到其他页面，再回来刷新过吗？是否还有报错？

这个报错我记得已经规避过了，暂时不清楚原因🧐

**Comment by q943613777** [comment]
> 1. 这个情况出现了几次
> 2. 出现这个问题之后，有切换到其他页面，再回来刷新过吗？是否还有报错？
> 
> 这个报错我记得已经规避过了，暂时不清楚原因🧐

1.出现过3次，之前2次退出软件重开就恢复正常了，这次没有退出，过了大概快3个小时看到恢复正常了
2.前2次也切换过页面，试了多次没恢复就正常退出软件重开。第3次出现这个情况之后也有切过其他页面多次，没恢复正常就没在意，做其他事情去了。

**Comment by hanaTsuk1** [comment]
还挺频繁的  我注意到你用的是firefox nightly  我之后看看
你可以留意一下  打开firefox nightly拉取和不打开的时候 有没有什么不同

**Comment by q943613777** [comment]
> 还挺频繁的 我注意到你用的是firefox nightly 我之后看看 你可以留意一下 打开firefox nightly拉取和不打开的时候 有没有什么不同
今天无意中出现了，录了个视频，放在阿里云盘了
提取 42fx
http://985.so/9p079

**Comment by hanaTsuk1** [comment]
是想说打开开发者工具，出现应用崩溃的情况吗

**Comment by q943613777** [comment]
> 是想说打开开发者工具，出现应用崩溃的情况吗

不是，现在能大概率重现应该是把监听进程删除这个操作，有挺大概率出现

**Comment by hanaTsuk1** [comment]
我完全没理解你想要表达的意思

如果你有兴趣找出报错的原因，可以了解一下这个
https://github.com/shion-app/history/blob/master/src/database.rs#L189

**Comment by hanaTsuk1** [comment]
最近还会经常出现这个bug吗？试一下这个

[shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16084885/shion_0.11.15_x64-setup.zip)

**Comment by q943613777** [comment]
> 最近还会经常出现这个bug吗？试一下这个
> 
> [shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16084885/shion_0.11.15_x64-setup.zip)

试了这个还是一样会出现
![image](https://github.com/shion-app/shion/assets/53282874/58adf3f7-2b00-4292-bfd9-0d85d019bb9c)
![有问题](https://github.com/shion-app/shion/assets/53282874/676e8902-0d01-43f2-b2e6-cc42c651d23b)

[shion.log](https://github.com/user-attachments/files/16086503/shion.log)

**Comment by hanaTsuk1** [comment]
这个是监听白名单碰到重复添加时的报错，没啥问题

我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂

**Comment by q943613777** [comment]
> 这个是监听白名单碰到重复添加时的报错，没啥问题
> 
> 我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂

这次没看到进程无法访问的打印，之前我以为刷新一直转圈圈是因为进程无法访问导致。明天有空我再试试

**Comment by hanaTsuk1** [comment]
> > 这个是监听白名单碰到重复添加时的报错，没啥问题
> > 我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂
> 
> 这次没看到进程无法访问的打印，之前我以为刷新一直转圈圈是因为进程无法访问导致。明天有空我再试试

👌  看网络那一栏  就能明确看到请求

**Comment by q943613777** [comment]
> > > 这个是监听白名单碰到重复添加时的报错，没啥问题
> > > 我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂
> > 
> > 
> > 这次没看到进程无法访问的打印，之前我以为刷新一直转圈圈是因为进程无法访问导致。明天有空我再试试
> 
> 👌 看网络那一栏 就能明确看到请求
看下是这个不
![image](https://github.com/shion-app/shion/assets/53282874/6f391b71-d418-4285-93d9-e1616744caa1)

**Comment by hanaTsuk1** [comment]
> > > > 这个是监听白名单碰到重复添加时的报错，没啥问题
> > > > 我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂
> > > 
> > > 
> > > 这次没看到进程无法访问的打印，之前我以为刷新一直转圈圈是因为进程无法访问导致。明天有空我再试试
> > 
> > 
> > 👌 看网络那一栏 就能明确看到请求
> > 看下是这个不
> > ![image](https://private-user-images.githubusercontent.com/53282874/345492843-6f391b71-d418-4285-93d9-e1616744caa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjEwNzEsIm5iZiI6MTcyMDAyMDc3MSwicGF0aCI6Ii81MzI4Mjg3NC8zNDU0OTI4NDMtNmYzOTFiNzEtZDQxOC00Mjg1LTkzZDktZTE2MTY3NDRjYWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE1MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjc1NzU5OTcyOGRlZGVmNGY5OTc2YTFkYjQ2ZDdlZTljNTk2MGQzN2M1MTNhNWVlZjhjNDJhZmQ4MWM3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_ChwaSx_131pCPWxpRftDKQa_PfO1PCHwGzBzjP4Xc)

是的  看一下参数和报错

**Comment by q943613777** [comment]
> > > > > 这个是监听白名单碰到重复添加时的报错，没啥问题
> > > > > 我主要是弄那个刷新的问题，看有没有**进程无法访问**这个问题。但你这个刷新一直转是啥情况，我记得之前就加上了处理😂
> > > > 
> > > > 
> > > > 这次没看到进程无法访问的打印，之前我以为刷新一直转圈圈是因为进程无法访问导致。明天有空我再试试
> > > 
> > > 
> > > 👌 看网络那一栏 就能明确看到请求
> > > 看下是这个不
> > > ![image](https://private-user-images.githubusercontent.com/53282874/345492843-6f391b71-d418-4285-93d9-e1616744caa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjEwNzEsIm5iZiI6MTcyMDAyMDc3MSwicGF0aCI6Ii81MzI4Mjg3NC8zNDU0OTI4NDMtNmYzOTFiNzEtZDQxOC00Mjg1LTkzZDktZTE2MTY3NDRjYWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE1MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNjc1NzU5OTcyOGRlZGVmNGY5OTc2YTFkYjQ2ZDdlZTljNTk2MGQzN2M1MTNhNWVlZjhjNDJhZmQ4MWM3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_ChwaSx_131pCPWxpRftDKQa_PfO1PCHwGzBzjP4Xc)
> 
> 是的 看一下参数和报错
{name: "Microsoft Edge", start: 1720020232124, end: 1720020622562} end : 1720020622562 name : "Microsoft Edge" start : 1720020232124

**Comment by hanaTsuk1** [comment]
错误信息是啥😂

**Comment by q943613777** [comment]
> 错误信息是啥😂

是这个不
![image](https://github.com/shion-app/shion/assets/53282874/aeb84690-ddde-4feb-a80a-75a7d159b37a)

**Comment by hanaTsuk1** [comment]
不是  只有这个的话  今天就这样了  麻烦你了
之后我再想想

**Comment by hanaTsuk1** [comment]
再试一下这个，看日志
我想知道每次都报错吗？每次都是同一个浏览器吗？

[shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16093237/shion_0.11.15_x64-setup.zip)

**Comment by q943613777** [comment]
> 再试一下这个，看日志 我想知道每次都报错吗？每次都是同一个浏览器吗？ 拉取过程中会生成临时文件，看日志temp file path显示的路径在结束后是否还存在
> 
> [shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16093516/shion_0.11.15_x64-setup.zip)
貌似还会出现，相同操作不是每次都会出现问题，概率出现
最近都在使用edge，电脑还装了Chrome、Firefox，但最近没有用过
![image](https://github.com/shion-app/shion/assets/53282874/0e1d5bc9-1578-49ef-adb7-4afb7565936c)
![image](https://github.com/shion-app/shion/assets/53282874/9db7df80-1e7e-4ead-b73c-0a83b686db8a)
![image](https://github.com/shion-app/shion/assets/53282874/b5382eff-b3b3-4f6d-a12a-4a6ca498dab0)



[shion.log](https://github.com/user-attachments/files/16098128/shion.log)

**Comment by hanaTsuk1** [comment]
你没用我发的最新的包吗  怎么日志有点对不上  麻烦再测一下🙏

每次都是同一个浏览器报错吗？看你这边报错是火狐
看负载和预览就行了
拉取过程中会生成临时文件，看日志temp file path显示的路径在结束后是否还存在


-----

然后再测一下这个

[shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16087780/shion_0.11.15_x64-setup.zip)

看报错是不是

> "remove file error: 另一个程序正在使用此文件，进程无法访问。 (os error 32)"

**Comment by q943613777** [comment]
> 你没用我发的最新的包吗 怎么日志有点对不上 麻烦再测一下🙏
> 
> 每次都是同一个浏览器报错吗？看你这边报错是火狐 看负载和预览就行了 拉取过程中会生成临时文件，看日志temp file path显示的路径在结束后是否还存在
> 
> 然后再测一下这个
> 
> [shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16087780/shion_0.11.15_x64-setup.zip)
> 
> 看报错是不是
> 
> > "remove file error: 另一个程序正在使用此文件，进程无法访问。 (os error 32)"
奇怪，我记得下午重新下载过了，这次特意挂了魔法下载，看日志是有无法访问的打印
![image](https://github.com/shion-app/shion/assets/53282874/4624daf0-342c-46f8-83da-a45e0e734d61)
![image](https://github.com/shion-app/shion/assets/53282874/7e3b4412-4e3b-4a9b-854d-ce41ec13b05e)
![image](https://github.com/shion-app/shion/assets/53282874/3120354d-6c7e-4128-8d69-aae7efe437db)

**Comment by q943613777** [comment]
我确实是只开了edge，没开firefox，但参数显示firefox就很奇怪

**Comment by hanaTsuk1** [comment]
跟你打不打开firefox没关系   只要导入了   就会一起拉取

已经可以确认问题的关键了👌

**Comment by hanaTsuk1** [comment]
[shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16107311/shion_0.11.15_x64-setup.zip)

防止尴尬  还是等你测一下再发布  有空的时候看一下

**Comment by q943613777** [comment]
> [shion_0.11.15_x64-setup.zip](https://github.com/user-attachments/files/16107311/shion_0.11.15_x64-setup.zip)
> 
> 防止尴尬 还是等你测一下再发布 有空的时候看一下

相同操作试了20次左右没出现无法访问和卡刷新问题，之前操作10次能出现3、4次，应该修好了。

**Comment by hanaTsuk1** [comment]
好的

C:\Users\{用户名}\AppData\Roaming\hanaTsuk1.shion\plugins\history\temp
看看有没有文件

**Comment by q943613777** [comment]
> 好的
> 
> C:\Users\{用户名}\AppData\Roaming\hanaTsuk1.shion\plugins\history\temp 看看有没有文件

没有，空的

**Comment by hanaTsuk1** [comment]
👌 这个我就先关了
