### ISSUE TITLE
[bug] 导入浏览器历史记录提示导入出错

### ISSUE THREAD

**Issue by happytbs** [shion-app/shion#24]
### Describe the bug

导入浏览器历史记录提示导入出错，电脑的Firefox已经卸载，只有Chrome和Edge。
![image](https://github.com/shion-app/shion/assets/74001578/78f965e5-eefb-4ce7-b149-a931ecb61dc4)
![image](https://github.com/shion-app/shion/assets/74001578/f2482819-fe67-4962-a59c-d87752877ef0)

### Version

v0.11.4

### Steps to reproduce

1、点击左上角视图
2、菜单点击“浏览器历史记录”
3、最后点击导入数据和确认

### Additional information

[shion.log](https://github.com/user-attachments/files/15520444/shion.log)

**Comment by q943613777** [comment]
[https://github.com/shion-app/shion/issues/19](url)
貌似这里有chrome和edge的解决方法，可以试试

**Comment by happytbs** [comment]
> [https://github.com/shion-app/shion/issues/19](url) 貌似这里有chrome和edge的解决方法，可以试试

链接啥也没有……

**Comment by q943613777** [comment]
> > [https://github.com/shion-app/shion/issues/19](url) 貌似这里有chrome和edge的解决方法，可以试试
> 
> 链接啥也没有……

#19   看下这个，下面回复有Chrome和Edge的

**Comment by hanaTsuk1** [comment]
这个报错和上面说的没关系
要不你重启试试

除了这三个步骤，没做其他操作了吗

**Comment by hanaTsuk1** [comment]
我做了一些修改，如果方便的话，麻烦帮忙测试一下，谢谢
https://github.com/shion-app/shion/releases/download/v0.12.0/shion_0.12.0_x64-setup.exe

**Comment by q943613777** [comment]
> 我做了一些修改，如果方便的话，麻烦帮忙测试一下，谢谢 https://github.com/shion-app/shion/releases/download/v0.12.0/shion_0.12.0_x64-setup.exe

试了新版没问题了，可以正常导入。

**Comment by hanaTsuk1** [comment]
@q943613777 我在问他  他的情况和你的不一样

**Comment by happytbs** [comment]
已解决，莫名其妙就好了

**Comment by hanaTsuk1** [comment]
> 已解决，莫名其妙就好了

好的，意思是没有用最新版本就好了吗

**Comment by happytbs** [comment]
> > 已解决，莫名其妙就好了
> 
> 好的，意思是没有用最新版本就好了吗

重新安装了chrome貌似解决了，更多信息无法提供

**Comment by hanaTsuk1** [comment]
> > > 已解决，莫名其妙就好了
> > 
> > 
> > 好的，意思是没有用最新版本就好了吗
> 
> 重新安装了chrome貌似解决了，更多信息无法提供

了解👌

**Comment by hanaTsuk1** [comment]
多说一句，如果你还使用这个软件的话

你现在用的版本v0.11.4已经不能直接更新了，需要重新下载v0.13.0
