### ISSUE TITLE
[bug] 搜索浏览记录，点击两次浏览记录之后，程序必定卡死

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#28]
### Describe the bug

![卡死](https://github.com/shion-app/shion/assets/53282874/a656a763-9cf8-4f82-867e-069fb1f77e0f)

### Version

v0.11.4

### Steps to reproduce

1、打开软件，在时间线界面
2、使用快捷键 Ctrl+F 调出搜索框
3、输入搜索内容后，点击两条历史记录

### Additional information

locale: zh-CN
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0

**Comment by q943613777** [comment]
两次没卡死的话，多点几次就会出现

**Comment by hanaTsuk1** [comment]
只在打开开发者工具时复现，tauri相关，暂时搁置

**Comment by q943613777** [comment]
> 只在打开开发者工具时复现，tauri相关，暂时搁置

好的

**Comment by hanaTsuk1** [comment]
[v0.11.22](https://github.com/shion-app/shion/releases/tag/v0.11.22)解决
