### ISSUE TITLE
[bug] 活跃状态日历和每日活跃从3行显示更换成1行显示没更新显示状态，要切换页签才更新

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#31]
### Describe the bug

![更新设定没效果](https://github.com/shion-app/shion/assets/53282874/ba915476-3e6f-4bac-8811-c81032c83a1d)

### Version

v0.11.7

**Comment by hanaTsuk1** [comment]
已修复  另外加了一下限制

**Comment by q943613777** [comment]
验证到已修复
