### ISSUE TITLE
[bug] 只打开了一个网页，刷新的时候会出现两条相同的记录，过一段时间再刷新变成两个事件

### ISSUE THREAD

**Issue by q943613777** [shion-app/shion#34]
### Describe the bug

![相同记20240622002936061录](https://github.com/shion-app/shion/assets/53282874/47c87afa-c760-4b9d-a2bf-0db4873fcfba)

![image](https://github.com/shion-app/shion/assets/53282874/b361970d-182e-4b25-ae7f-03fd49ba93f1)
![image](https://github.com/shion-app/shion/assets/53282874/90f31a38-a8ce-4d86-8502-a8097aee57f5)

### Version

v0.11.8

### Steps to reproduce

1.打开edge浏览器
2.随意打开一个网页
3.刷新数据并查看数据

### Additional information

[shion.log](https://github.com/user-attachments/files/15929073/shion.log)

**Comment by hanaTsuk1** [comment]
浏览器的数据就是这样  你把历史记录打开也能看到重复的

**Comment by q943613777** [comment]
外部原因导致看起来像BUG
