### ISSUE TITLE
[bug] 每日活跃类型的组件当垂直排列时时间貌似相反了

### ISSUE THREAD

**Issue by qiujubin** [shion-app/shion#39]
### Describe the bug

<img width="253" alt="image" src="https://github.com/shion-app/shion/assets/44926027/74ce2a4d-8f52-4b39-91ca-19dfac5f6674">
上图为非垂直排列时

<img width="251" alt="image" src="https://github.com/shion-app/shion/assets/44926027/1409fd4b-b461-4729-b221-a2d9b40ef02e">
上图为垂直时

貌似是小时的时间反了

### Version

v0.11.15

**Comment by hanaTsuk1** [comment]
就是这么设计的

**Comment by qiujubin** [comment]
啊不是，我指的是柱状图的值与对应的时间，比如上面的图，非垂直排列时那蓝色的在13时左右，垂直排列时它在10时左右了

**Comment by hanaTsuk1** [comment]
没事👌
已经发布了  在应用内更新就行了
