### ISSUE TITLE
[bug] 无法设置开机启动，报错参数错误。 (0x80070057)

### ISSUE THREAD

**Issue by guiyyo** [shion-app/shion#42]
### Describe the bug

一直无法设置开机启动，杀软啥的关了都不行

### Version

v0.11.17

### Additional information

[2024-07-11][09:35:12][DEBUG][tauri_plugin_shion_watcher::watcher] add program: C:\Program Files (x86)\Microsoft\EdgeWebView\Application\126.0.2592.61\msedgewebview2.exe
[2024-07-11][09:35:12][ERROR][webview::unknown] autostart error: 参数错误。 (0x80070057)
[2024-07-11][09:35:12][DEBUG][tauri_plugin_shion_watcher::watcher] remove program: C:\Program Files (x86)\Microsoft\EdgeWebView\Application\126.0.2592.61\msedgewebview2.exe

**Comment by guiyyo** [comment]
确认了是自动运行的，但还是无法设置开机启动
![image](https://github.com/user-attachments/assets/101d997e-9738-4ff3-9fe4-bec285500050)

**Comment by hanaTsuk1** [comment]
我没有找到太多有用的信息，你可以试试下面的办法

系统文件的损坏可能导致计划任务无法正常工作。可以运行系统文件检查器（sfc）来修复损坏的系统文件：

1. 打开命令提示符（以管理员身份）
2. 运行命令 sfc /scannow
3. 等待扫描完成，修复任何检测到的问题

你可以看看其他任务有没有正常在运行（看上次运行时间）

![mmc_lZfzEkywHx](https://github.com/user-attachments/assets/144988f3-9bc6-427d-bde6-db10bafbe7d0)

**Comment by guiyyo** [comment]
我确认了系统无任何损坏，并且任务计划程序中其他程序计划运行正常
![image](https://github.com/user-attachments/assets/ab0cc346-0d3c-4ff7-a583-950cc17ffba5)
![image](https://github.com/user-attachments/assets/d94ef1a1-1aa3-4089-9c92-35294f910647)

**Comment by hanaTsuk1** [comment]
我看到你有shion的那个任务了（左边最下面一个文件夹）  你打开看看
看看有没有一个auto start的任务  双击看看里面的设置

**Comment by guiyyo** [comment]
里面是空的，啥都没有
![image](https://github.com/user-attachments/assets/37849758-1fde-4942-a650-a4a6d7c28fd6)

**Comment by hanaTsuk1** [comment]
好的  我再找找原因
我先告诉你手动创建  让你能使用把
1. 在shion下`创建任务`（右侧操作），在`常规`一栏，输入名称，勾选`使用最高权限运行`
2. 新建触发器，`开始任务`勾选登录时，下面的`高级设置`延迟任务时间设置10秒
3. 新建操作，操作为`启动程序`，点击`浏览`找到shion.exe的路径
4. 在`条件`一栏，把`电源`的钩都取消

**Comment by guiyyo** [comment]
我在控制台里看到有更详细的报错，看能不能协助定位问题
![image](https://github.com/user-attachments/assets/122bdc3d-4b0d-4301-8c6d-8a79a0fd42a4)
![image](https://github.com/user-attachments/assets/06124644-208f-4fff-ab36-5f3bf90bd733)
![image](https://github.com/user-attachments/assets/c9bb3b9d-5f01-4fb4-bcd3-1834144461ed)
![image](https://github.com/user-attachments/assets/41463bbf-e5fb-4bf2-8989-8fa66409d03e)

**Comment by hanaTsuk1** [comment]
设置的整个过程都在rust端  网页这边只是发了一个请求  现在报错信息已经返回了  
只有修改了代码才能具体定位  后续可能要麻烦你弄一下

**Comment by guiyyo** [comment]
OK，可以配合

**Comment by hanaTsuk1** [comment]
[shion-dev_0.11.18_x64-setup.zip](https://github.com/user-attachments/files/16258531/shion-dev_0.11.18_x64-setup.zip)

试一下这个

**Comment by guiyyo** [comment]
这个可以，没问题，计划任务里也有这个启动项

**Comment by guiyyo** [comment]
这个可以，没问题，计划任务里也有这个启动项

**Comment by hanaTsuk1** [comment]
好的  开机启动这部分有其他改动  我会过段时间发布

> 测试完  记得关闭测试包的开机启动

**Comment by hanaTsuk1** [comment]
v0.11.23修复
