### ISSUE TITLE
[bug]用了几天了，什么都没记录到

### ISSUE THREAD

**Issue by note4** [shion-app/shion#7]
### Describe the bug

![image](https://github.com/shion-app/shion/assets/6513389/6b7a4f6a-ff55-49bf-b4b5-391079889b37)

### Version

v0.9.1

**Comment by hanaTsuk1** [comment]
你想说的是程序自动计时吗？你打开监听页面，只有添加了的程序才会被记录

**Comment by alterxyz** [comment]
我开始也遇到了这个"问题"
或许新手引导或者演示可以多做一点

**Comment by hanaTsuk1** [comment]
> 我开始也遇到了这个"问题" 或许新手引导或者演示可以多做一点

👌

**Comment by JYUNAC** [comment]
我也遇到了這個問題, 幸好找到這個頁面。
